apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sensitive-alpaca-nodejs 
  janus-idp.io/tekton: sensitive-alpaca-nodejs
  backstage.io/kubernetes-id: sensitive-alpaca-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sensitive-alpaca-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  