apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sensitive-alpaca-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sensitive-alpaca-nodejs 
  name: sensitive-alpaca-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sensitive-alpaca-nodejs 
